spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu #按照参数路由，如果请求体参数带有baidu，就去百度

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq