server:
  port: 40000

spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 127.0.0.1   #理论上，购物车应该在专门的一个redis，培训嘛，就用一个redis吧
    port: 6379


#配置线程池(需要先写配置类）
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10